FROM rust:1.88-slim-bookworm AS tun2proxy-build

ENV GIT_HASH=crates-io

RUN cargo install --locked --bin tun2proxy-bin tun2proxy

# harness-hat base — Ubuntu 24.04 LTS (Noble Numbat)
#
# Build (from repo root):
#   docker build -t harness-hat-base:local -f docker/harness-hat-base.dockerfile .
#
# Run command is generated by the harness-hat TUI for your project.
#
# ── Network filtering and CA trust ───────────────────────────────────────────
# harness-hat routes container traffic through its MITM proxy and injects the CA
# cert path via environment variables at run time.  Most runtimes are covered
# automatically:
#
#   SSL_CERT_FILE / CURL_CA_BUNDLE          — OpenSSL, curl, Go, Ruby, PHP
#   NODE_EXTRA_CA_CERTS / DENO_CERT         — Node.js, npm, yarn, bun, Deno
#   REQUESTS_CA_BUNDLE / AWS_CA_BUNDLE      — Python (requests/httpx/pip), AWS SDK
#   GIT_SSL_CAINFO                          — git over HTTPS
#   GRPC_DEFAULT_SSL_ROOTS_FILE_PATH        — gRPC (all language runtimes)
#
# harness-hat-init.sh also runs update-ca-certificates (when root) to update the system
# store, which covers .NET / C# (HttpClient, RestSharp, etc.).  Omit --user
# from your docker run flags to allow this; with --user 1000:1000 the system
# store update is skipped (env-var-based runtimes still work fine).
#
# Java / JVM (OkHttp, Apache HttpClient, java.net.http, Ktor, etc.) maintains
# its own keystore and ignores the system store and env vars.  The CA cert is
# only bind-mounted at run time, so keytool must run at container start, not
# during the image build.  Extend harness-hat-init.sh in your downstream Dockerfile:
#
#   keytool -importcert -noprompt -alias harness-hat -cacerts \
#     -storepass changeit \
#     -file /usr/local/share/ca-certificates/harness-hat-ca.crt 2>/dev/null || true
#
# Rust / rustls + webpki-roots: uses a compiled-in Mozilla bundle and ignores
# all env vars and the system store.  To intercept traffic from such binaries,
# either patch the application to load extra roots at startup, or rebuild with
# the native-tls / openssl-sys backend so SSL_CERT_FILE is honoured.

FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      nano \
      git \
      python3 \
      python3-pip \
      python3-venv \
      unzip \
      bubblewrap \
      build-essential \
      iproute2 \
      iptables \
      gosu \
    && rm -rf /var/lib/apt/lists/*

# Install a current Node runtime for agent CLIs (Gemini CLI requires Node 20+).
# The NodeSource `nodejs` package already carries npm, and Ubuntu's `npm`
# package conflicts with it.
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get update && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/hostdo.py /usr/local/bin/hostdo
RUN chmod 755 /usr/local/bin/hostdo
COPY scripts/killme.py /usr/local/bin/killme
RUN chmod 755 /usr/local/bin/killme
ARG TUN2PROXY_RELEASE=latest
RUN set -eu; \
    if [ -x /usr/local/cargo/bin/tun2proxy-bin ]; then \
        install -m 755 /usr/local/cargo/bin/tun2proxy-bin /usr/local/bin/tun2proxy-bin; \
    else \
        case "$(dpkg --print-architecture)" in \
            amd64) asset="tun2proxy-x86_64-unknown-linux-gnu.zip" ;; \
            arm64) asset="tun2proxy-aarch64-unknown-linux-gnu.zip" ;; \
            *) echo "harness-hat: unsupported architecture for tun2proxy release fallback" >&2; exit 1 ;; \
        esac; \
        if [ "$TUN2PROXY_RELEASE" = "latest" ]; then \
            release_json="$(curl -fsSL https://api.github.com/repos/tun2proxy/tun2proxy/releases/latest)"; \
        else \
            release_json="$(curl -fsSL "https://api.github.com/repos/tun2proxy/tun2proxy/releases/tags/${TUN2PROXY_RELEASE}")"; \
        fi; \
        download_url="$(printf '%s' "$release_json" | python3 -c 'import json,sys; obj=json.load(sys.stdin); name=sys.argv[1]; print(next(a["browser_download_url"] for a in obj["assets"] if a["name"] == name))' "$asset")"; \
        tmpdir="$(mktemp -d)"; \
        curl -fsSL "$download_url" -o "$tmpdir/tun2proxy.zip"; \
        python3 -c 'import pathlib, sys, zipfile; zf=zipfile.ZipFile(sys.argv[1]); zf.extractall(sys.argv[2])' "$tmpdir/tun2proxy.zip" "$tmpdir"; \
        install -m 755 "$tmpdir/tun2proxy-bin" /usr/local/bin/tun2proxy-bin; \
        rm -rf "$tmpdir"; \
    fi; \
    test -x /usr/local/bin/tun2proxy-bin

# Trusts the harness-hat MITM CA cert bind-mounted at run time (root only).
RUN cat > /usr/local/bin/harness-hat-init.sh << 'SCRIPT'
#!/bin/sh
set -e
HH_CERT="/usr/local/share/ca-certificates/harness-hat-ca.crt"
if [ -f "$HH_CERT" ] && [ "$(id -u)" = "0" ]; then
    update-ca-certificates 2>/dev/null || true
fi

# Best-effort: ensure bind-mounted auth/session state under /home/ubuntu is
# readable by uid 1000 (common issue on macOS/Linux).
if [ "$(id -u)" = "0" ]; then
    if [ -f /home/ubuntu/.claude.json ]; then
        chown 1000:1000 /home/ubuntu/.claude.json 2>/dev/null || true
        chmod 600 /home/ubuntu/.claude.json 2>/dev/null || true
    fi
    if [ -d /home/ubuntu/.claude ]; then
        chown -R 1000:1000 /home/ubuntu/.claude 2>/dev/null || true
        chmod 700 /home/ubuntu/.claude 2>/dev/null || true
        chmod -R u+rwX /home/ubuntu/.claude 2>/dev/null || true
    fi
fi

# Copy staged Claude credentials into place.  harness-hat mounts the host
# keychain credential at a staging path to avoid nested bind-mount conflicts.
HH_STAGED_CREDS="/tmp/.harness-hat-claude-credentials.json"
if [ -f "$HH_STAGED_CREDS" ]; then
    CLAUDE_DIR="/home/ubuntu/.claude"
    mkdir -p "$CLAUDE_DIR" 2>/dev/null || true
    cp "$HH_STAGED_CREDS" "$CLAUDE_DIR/.credentials.json" 2>/dev/null || true
    chown 1000:1000 "$CLAUDE_DIR/.credentials.json" 2>/dev/null || true
    chmod 600 "$CLAUDE_DIR/.credentials.json" 2>/dev/null || true
fi

# Optional: strict network enforcement.
# TUN mode captures outbound TCP at the routing layer and forwards it through
# the harness-hat scoped HTTP proxy via tun2proxy.  This does not rely on the
# application honoring HTTP(S)_PROXY or ALL_PROXY.  UDP/QUIC are intentionally
# blocked; DNS to Docker's embedded resolver is allowed.
if [ "${HARNESS_HAT_STRICT_NETWORK:-0}" = "1" ]; then
    if [ "$(id -u)" != "0" ]; then
        echo "harness-hat: strict_network requires root" >&2
        exit 1
    fi
    if [ -z "${HARNESS_HAT_SCOPED_PROXY_ADDR:-}" ] || [ -z "${HARNESS_HAT_URL:-}" ]; then
        echo "harness-hat: strict_network missing HARNESS_HAT_SCOPED_PROXY_ADDR or HARNESS_HAT_URL" >&2
        exit 1
    fi

    if [ ! -c /dev/net/tun ]; then
        echo "harness-hat: strict_network requires /dev/net/tun (Docker Desktop usually needs --privileged)" >&2
        exit 1
    fi

    # ── Pick the iptables binary that actually works ──────────────────────
    # Ubuntu 24.04 defaults to iptables-nft.  Docker Desktop's LinuxKit VM
    # may only support iptables-legacy.  Probe both and use the first that
    # succeeds at listing the filter/OUTPUT chain.
    IPT=""
    IP6T=""
    for candidate in iptables-legacy iptables; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -w -t filter -L OUTPUT -n >/dev/null 2>&1; then
            IPT="$candidate"
            break
        fi
    done
    for candidate in ip6tables-legacy ip6tables; do
        if command -v "$candidate" >/dev/null 2>&1 \
           && "$candidate" -w -t filter -L OUTPUT -n >/dev/null 2>&1; then
            IP6T="$candidate"
            break
        fi
    done
    if [ -z "$IPT" ]; then
        echo "harness-hat: strict_network requires a working iptables (tried iptables-legacy, iptables)" >&2
        exit 1
    fi

    proxy_host="${HARNESS_HAT_SCOPED_PROXY_ADDR%:*}"
    proxy_port="${HARNESS_HAT_SCOPED_PROXY_ADDR##*:}"
    exec_hostport="$(printf '%s' "$HARNESS_HAT_URL" | sed -E 's#^[a-zA-Z]+://##')"
    exec_scheme="$(printf '%s' "$HARNESS_HAT_URL" | sed -E 's#^([a-zA-Z]+)://.*#\1#')"
    [ -n "$exec_scheme" ] || exec_scheme="http"
    exec_host="${exec_hostport%:*}"
    exec_port="${exec_hostport##*:}"

    proxy_ip="$(getent ahostsv4 "$proxy_host" 2>/dev/null | awk '{print $1; exit}')"
    exec_ip="$(getent ahostsv4 "$exec_host" 2>/dev/null | awk '{print $1; exit}')"
    if [ -z "$proxy_ip" ] || [ -z "$exec_ip" ]; then
        echo "harness-hat: strict_network failed to resolve proxy ($proxy_host) or exec ($exec_host) hosts" >&2
        exit 1
    fi

    # Keep hostdo control traffic on the direct exec-bridge path.
    # In strict mode with virtual DNS, hostnames can resolve to synthetic
    # 198.18.0.0/15 addresses; using the resolved bridge IP avoids that.
    export HARNESS_HAT_URL="${exec_scheme}://${exec_ip}:${exec_port}"

    echo "harness-hat: strict_network using $IPT; proxy=$proxy_ip:$proxy_port exec=$exec_ip:$exec_port" >&2

    # ── Layer 1: strict egress filter ────────────────────────────────────
    # Allow only: loopback, tun0 (captured traffic), established/related,
    # Docker DNS, proxy, exec. Traffic written to tun0 is not raw egress;
    # tun2proxy consumes it in userspace and opens the real upstream sockets.
    # Anything escaping that path on a physical interface is rejected here.
    $IPT -w -t filter -N HH_EGRESS 2>/dev/null || $IPT -w -t filter -F HH_EGRESS
    $IPT -w -t filter -C OUTPUT -j HH_EGRESS 2>/dev/null || $IPT -w -t filter -I OUTPUT 1 -j HH_EGRESS
    $IPT -w -t filter -F HH_EGRESS
    $IPT -w -t filter -A HH_EGRESS -o lo -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -o tun0 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p udp -d 127.0.0.11 --dport 53 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d 127.0.0.11 --dport 53 -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d "$proxy_ip" --dport "$proxy_port" -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -p tcp -d "$exec_ip" --dport "$exec_port" -j ACCEPT
    $IPT -w -t filter -A HH_EGRESS -j REJECT 2>/dev/null || $IPT -w -t filter -A HH_EGRESS -j DROP

    # IPv6: reject everything to avoid long hangs on AAAA/QUIC attempts.
    if [ -n "$IP6T" ]; then
        $IP6T -w -t filter -N HH_EGRESS 2>/dev/null || $IP6T -w -t filter -F HH_EGRESS
        $IP6T -w -t filter -C OUTPUT -j HH_EGRESS 2>/dev/null || $IP6T -w -t filter -I OUTPUT 1 -j HH_EGRESS
        $IP6T -w -t filter -F HH_EGRESS
        $IP6T -w -t filter -A HH_EGRESS -o lo -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -o tun0 -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
        $IP6T -w -t filter -A HH_EGRESS -j REJECT 2>/dev/null || $IP6T -w -t filter -A HH_EGRESS -j DROP
    fi

    # ── Layer 2: tun2proxy routing ───────────────────────────────────────
    # Bypass the scoped proxy and exec bridge addresses so tun2proxy can talk
    # to them directly.  Docker's DNS (127.0.0.11) remains reachable.
    TUN2PROXY_BIN="$(command -v tun2proxy-bin 2>/dev/null || true)"
    if [ -z "$TUN2PROXY_BIN" ]; then
        for candidate in \
            /usr/local/bin/tun2proxy-bin \
            /usr/local/cargo/bin/tun2proxy-bin \
            /root/.cargo/bin/tun2proxy-bin
        do
            if [ -x "$candidate" ]; then
                TUN2PROXY_BIN="$candidate"
                break
            fi
        done
    fi
    if [ -z "$TUN2PROXY_BIN" ]; then
        echo "harness-hat: tun2proxy-bin not found in PATH or common cargo locations" >&2
        exit 1
    fi
    "$TUN2PROXY_BIN" \
        --setup \
        --proxy "http://${proxy_ip}:${proxy_port}" \
        --dns virtual \
        --bypass "$proxy_ip" \
        --bypass "$exec_ip" \
        >/tmp/harness-hat-tun2proxy.log 2>&1 &
    HH_TUN2PROXY_PID=$!
    sleep 1
    if ! kill -0 "$HH_TUN2PROXY_PID" 2>/dev/null; then
        echo "harness-hat: tun2proxy failed to start" >&2
        cat /tmp/harness-hat-tun2proxy.log >&2 || true
        exit 1
    fi

    # With TUN capture active, application-level proxy env vars are not needed
    # and can cause double-proxying in clients that partially support them.
    unset HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY
    unset http_proxy https_proxy all_proxy no_proxy

    echo "harness-hat: strict_network ready (tun2proxy + iptables filter)" >&2
fi

clear 2>/dev/null || true

if [ "$(id -u)" = "0" ]; then
    exec gosu 1000:1000 "$@"
fi
exec "$@"
SCRIPT
RUN chmod 755 /usr/local/bin/harness-hat-init.sh

# ubuntu:24.04 ships with an 'ubuntu' user at uid/gid 1000.
USER ubuntu
WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/harness-hat-init.sh"]
CMD ["/bin/bash"]
